/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Nicolas Herrera
 */
public class VentanaMercado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaMercado() {
        initComponents();
        this.pagInicial();
        this.addBotonesPrincipalListener(new CambiarPaginaListener());
        this.addBotonesPrincipalColorListener(new ManejadoraDeMouse());
        this.addBotonesFormularioListener(new BotonesFormularioListener());
        this.addTablaClienteListener(new TablaClienteListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jpBotones = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnClientes = new JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnProveedores = new JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnInventario = new JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnComprar = new JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnVender = new JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnCompras = new JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnVentas = new JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jpPrincipal = new javax.swing.JPanel();
        jpInicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpCliente = new javax.swing.JPanel();
        jpFormularioCliente = new javax.swing.JPanel();
        txtIdCliente = new javax.swing.JTextField();
        lblNitCliente = new javax.swing.JLabel();
        txtNitCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblTelefonoCliente = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        lblDireccionCliente = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        jspTablaCliente = new javax.swing.JScrollPane();
        jtTablaCliente = new JTable();
        jpBotonesCliente = new javax.swing.JPanel();
        btnAgregarCliente = new JButton();
        btnEditarCliente = new JButton();
        btnEliminarCliente = new JButton();
        jpProveedor = new javax.swing.JPanel();
        jpFormularioProveedor = new javax.swing.JPanel();
        txtIdProveedor = new javax.swing.JTextField();
        lblNitProveedor = new javax.swing.JLabel();
        txtNitProveedor = new javax.swing.JTextField();
        lblNombreProveedor = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        lblTelefonoProveedor = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        lblDireccionProveedor = new javax.swing.JLabel();
        txtDireccionProveedor = new javax.swing.JTextField();
        lblRazonSocialProveedor = new javax.swing.JLabel();
        txtRazonSocialProveedor = new javax.swing.JTextField();
        jspTablaProveedor = new javax.swing.JScrollPane();
        jtTablaProveedor = new JTable();
        jpBotonesProveedor = new javax.swing.JPanel();
        btnAgregarProveedor = new JButton();
        btnEditarProveedor = new JButton();
        btnEliminarProveedor = new JButton();
        jpInventario = new javax.swing.JPanel();
        jpFormularioInventario = new javax.swing.JPanel();
        txtIdProducto = new javax.swing.JTextField();
        lblCodigoProducto = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        lblNombreProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblPrecioCompraProducto = new javax.swing.JLabel();
        txtPrecioCompraProducto = new javax.swing.JTextField();
        lblPrecioVentaProducto = new javax.swing.JLabel();
        txtPrecioVentaProducto = new javax.swing.JTextField();
        lblStockProducto = new javax.swing.JLabel();
        txtStockProducto = new javax.swing.JTextField();
        lblProveedorInventario = new javax.swing.JLabel();
        txtProveedorProducto = new javax.swing.JTextField();
        jspTablaInventario = new javax.swing.JScrollPane();
        jtTablaInventario = new JTable();
        jpBotonesInventario = new javax.swing.JPanel();
        btnEditarProducto = new JButton();
        btnEliminarProducto = new JButton();
        jpComprar = new javax.swing.JPanel();
        jpFormularioComprar = new javax.swing.JPanel();
        lblCodigoCompra = new javax.swing.JLabel();
        txtCodigoComprar = new javax.swing.JTextField();
        lblNombreCompra = new javax.swing.JLabel();
        txtNombreComprar = new javax.swing.JTextField();
        lblPrecioCompraComprar = new javax.swing.JLabel();
        txtPrecioCompraComprar = new javax.swing.JTextField();
        lblPrecioVentaComprar = new javax.swing.JLabel();
        txtPrecioVentaComprar = new javax.swing.JTextField();
        lblStockComprar = new javax.swing.JLabel();
        txtStockComprar = new javax.swing.JTextField();
        lblProveedorComprar = new javax.swing.JLabel();
        jcbProveedorComprar = new javax.swing.JComboBox<>();
        jspTablaComprar = new javax.swing.JScrollPane();
        jtTablaComprar = new JTable();
        jpInferiorComprar = new javax.swing.JPanel();
        jpBotonesComprar = new javax.swing.JPanel();
        btnAgregarCompra = new JButton();
        btnRealizarCompra = new JButton();
        btnEliminarCompra = new JButton();
        jpValoresTotales = new javax.swing.JPanel();
        lblProductosTotalesComprar = new javax.swing.JLabel();
        lblPrecioTotalComprar = new javax.swing.JLabel();
        jpVender = new javax.swing.JPanel();
        jpFormularioComprar1 = new javax.swing.JPanel();
        lblProductoVender = new javax.swing.JLabel();
        jcbProductoVender = new javax.swing.JComboBox<>();
        lblStockVender = new javax.swing.JLabel();
        txtStockVender = new javax.swing.JTextField();
        lblClienteVender = new javax.swing.JLabel();
        jcbClienteVender = new javax.swing.JComboBox<>();
        jspTablaVender = new javax.swing.JScrollPane();
        jtTablaVender = new JTable();
        jpInferiorVender = new javax.swing.JPanel();
        jpBotonesVender = new javax.swing.JPanel();
        btnAgregarVenta = new JButton();
        btnRealizarVenta = new JButton();
        btnEliminarVenta = new JButton();
        jpValoresTotalesVenta = new javax.swing.JPanel();
        lblProductosTotalesVender = new javax.swing.JLabel();
        lblPrecioTotalVender = new javax.swing.JLabel();
        jpCompras = new javax.swing.JPanel();
        jpSuperiorCompras = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jspTablaCompras = new javax.swing.JScrollPane();
        jtTablaCompras = new JTable();
        jpInferiorCompras = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jpVentas = new javax.swing.JPanel();
        jpSuperiorVentas = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jspTablaVentas = new javax.swing.JScrollPane();
        jtTablaVentas = new JTable();
        jpInferiorVentas = new javax.swing.JPanel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jpEncabezado = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPERMERCADO UNIVALLE\n");
        setMinimumSize(new java.awt.Dimension(1700, 900));
        setPreferredSize(new java.awt.Dimension(1700, 900));
        setState(Frame.NORMAL);

        jpBotones.setBackground(new Color(52, 73, 85));
        jpBotones.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jpBotones.setLayout(new javax.swing.BoxLayout(jpBotones, javax.swing.BoxLayout.Y_AXIS));
        jpBotones.add(filler6);

        btnClientes.setBackground(new Color(249, 170, 51));
        btnClientes.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnClientes.setForeground(new Color(255, 255, 255));
        btnClientes.setIcon(new ImageIcon(getClass().getResource("/cliente.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setToolTipText("");
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setFocusable(false);
        btnClientes.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
        });
        btnClientes.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        btnClientes.setAlignmentX(CENTER_ALIGNMENT);
        btnClientes.setIconTextGap(8);
        jpBotones.add(btnClientes);
        jpBotones.add(filler4);

        btnProveedores.setBackground(new Color(249, 170, 51));
        btnProveedores.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnProveedores.setForeground(new Color(255, 255, 255));
        btnProveedores.setIcon(new ImageIcon(getClass().getResource("/proveedor.png"))); // NOI18N
        btnProveedores.setText("PROVEEDORES");
        btnProveedores.setBorderPainted(false);
        btnProveedores.setContentAreaFilled(false);
        btnProveedores.setFocusable(false);
        btnProveedores.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        btnProveedores.setAlignmentX(CENTER_ALIGNMENT);
        btnProveedores.setIconTextGap(8);
        jpBotones.add(btnProveedores);
        jpBotones.add(filler3);

        btnInventario.setBackground(new Color(249, 170, 51));
        btnInventario.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnInventario.setForeground(new Color(255, 255, 255));
        btnInventario.setIcon(new ImageIcon(getClass().getResource("/inventario.png"))); // NOI18N
        btnInventario.setText("INVENTARIO");
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setFocusable(false);
        btnInventario.setAlignmentX(CENTER_ALIGNMENT);
        btnInventario.setIconTextGap(8);
        jpBotones.add(btnInventario);
        jpBotones.add(filler2);

        btnComprar.setBackground(new Color(249, 170, 51));
        btnComprar.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnComprar.setForeground(new Color(255, 255, 255));
        btnComprar.setIcon(new ImageIcon(getClass().getResource("/compra.png"))); // NOI18N
        btnComprar.setText("COMPRAR");
        btnComprar.setToolTipText("");
        btnComprar.setBorderPainted(false);
        btnComprar.setContentAreaFilled(false);
        btnComprar.setFocusable(false);
        btnComprar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        btnComprar.setAlignmentX(CENTER_ALIGNMENT);
        btnComprar.setIconTextGap(8);
        jpBotones.add(btnComprar);
        jpBotones.add(filler1);

        btnVender.setBackground(new Color(249, 170, 51));
        btnVender.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnVender.setForeground(new Color(255, 255, 255));
        btnVender.setIcon(new ImageIcon(getClass().getResource("/venta.png"))); // NOI18N
        btnVender.setText("VENDER");
        btnVender.setBorderPainted(false);
        btnVender.setContentAreaFilled(false);
        btnVender.setFocusable(false);
        btnVender.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        btnVender.setAlignmentX(CENTER_ALIGNMENT);
        btnVender.setIconTextGap(8);
        jpBotones.add(btnVender);
        jpBotones.add(filler5);

        btnCompras.setBackground(new Color(249, 170, 51));
        btnCompras.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnCompras.setForeground(new Color(255, 255, 255));
        btnCompras.setIcon(new ImageIcon(getClass().getResource("/factura.png"))); // NOI18N
        btnCompras.setText("COMPRAS");
        btnCompras.setBorderPainted(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setFocusable(false);
        btnCompras.setAlignmentX(CENTER_ALIGNMENT);
        btnCompras.setIconTextGap(8);
        jpBotones.add(btnCompras);
        jpBotones.add(filler7);

        btnVentas.setBackground(new Color(249, 170, 51));
        btnVentas.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnVentas.setForeground(new Color(255, 255, 255));
        btnVentas.setIcon(new ImageIcon(getClass().getResource("/factura.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setFocusable(false);
        btnVentas.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        btnVentas.setAlignmentX(CENTER_ALIGNMENT);
        btnVentas.setIconTextGap(8);
        jpBotones.add(btnVentas);
        jpBotones.add(filler8);

        getContentPane().add(jpBotones, java.awt.BorderLayout.WEST);

        jpPrincipal.setLayout(new CardLayout());

        jpInicial.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 150));

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/tienda.png"))); // NOI18N
        jpInicial.add(jLabel1);

        jpPrincipal.add(jpInicial, "inicial");

        jpCliente.setLayout(new java.awt.BorderLayout());

        jpFormularioCliente.setBackground(new Color(74, 101, 114));
        jpFormularioCliente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        txtIdCliente.setEditable(false);
        txtIdCliente.setText("0");
        txtIdCliente.setEnabled(false);
        txtIdCliente.setFocusable(false);
        txtIdCliente.setMinimumSize(new java.awt.Dimension(80, 23));
        txtIdCliente.setOpaque(true);
        txtIdCliente.setPreferredSize(new java.awt.Dimension(80, 23));
        txtIdCliente.setVisible(false);
        jpFormularioCliente.add(txtIdCliente);

        lblNitCliente.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblNitCliente.setForeground(new Color(255, 255, 255));
        lblNitCliente.setText("NIT");
        jpFormularioCliente.add(lblNitCliente);

        txtNitCliente.setColumns(15);
        txtNitCliente.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtNitCliente.setToolTipText("");
        txtNitCliente.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtNitCliente.setMinimumSize(new java.awt.Dimension(4, 23));
        txtNitCliente.setPreferredSize(new java.awt.Dimension(199, 23));
        txtNitCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNitClienteActionPerformed(evt);
            }
        });
        jpFormularioCliente.add(txtNitCliente);

        lblNombreCliente.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblNombreCliente.setForeground(new Color(255, 255, 255));
        lblNombreCliente.setText("NOMBRE");
        jpFormularioCliente.add(lblNombreCliente);

        txtNombreCliente.setColumns(15);
        txtNombreCliente.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtNombreCliente.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtNombreCliente.setMinimumSize(new java.awt.Dimension(4, 23));
        txtNombreCliente.setPreferredSize(new java.awt.Dimension(199, 23));
        txtNombreCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        jpFormularioCliente.add(txtNombreCliente);

        lblTelefonoCliente.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblTelefonoCliente.setForeground(new Color(255, 255, 255));
        lblTelefonoCliente.setText("TELEFONO");
        jpFormularioCliente.add(lblTelefonoCliente);

        txtTelefonoCliente.setColumns(15);
        txtTelefonoCliente.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtTelefonoCliente.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtTelefonoCliente.setMinimumSize(new java.awt.Dimension(4, 23));
        txtTelefonoCliente.setPreferredSize(new java.awt.Dimension(199, 23));
        txtTelefonoCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });
        jpFormularioCliente.add(txtTelefonoCliente);

        lblDireccionCliente.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblDireccionCliente.setForeground(new Color(255, 255, 255));
        lblDireccionCliente.setText("DIRECCION");
        jpFormularioCliente.add(lblDireccionCliente);

        txtDireccionCliente.setColumns(15);
        txtDireccionCliente.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtDireccionCliente.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtDireccionCliente.setMinimumSize(new java.awt.Dimension(4, 23));
        txtDireccionCliente.setPreferredSize(new java.awt.Dimension(199, 23));
        txtDireccionCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtDireccionClienteActionPerformed(evt);
            }
        });
        jpFormularioCliente.add(txtDireccionCliente);

        jpCliente.add(jpFormularioCliente, java.awt.BorderLayout.NORTH);

        jtTablaCliente.setDefaultEditor(Object.class, null);
        jtTablaCliente.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        jtTablaCliente.getTableHeader().setFont(new Font("Montserrat", 1, 12)); // NOI18N
        jtTablaCliente.setModel(new DefaultTableModel(
                null,
                new String [] {
                        "ID","NIT", "NOMBRE", "TELEFONO", "DIRECCION"
                }
        ));
        jtTablaCliente.setEditingColumn(1);
        jtTablaCliente.setEditingRow(1);
        jtTablaCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTablaCliente.getTableHeader().setResizingAllowed(false);
        jtTablaCliente.getTableHeader().setReorderingAllowed(false);
        jspTablaCliente.setViewportView(jtTablaCliente);

        jpCliente.add(jspTablaCliente, java.awt.BorderLayout.CENTER);

        jpBotonesCliente.setBackground(new Color(74, 101, 114));
        jpBotonesCliente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 15));

        btnAgregarCliente.setBackground(new Color(0, 102, 51));
        btnAgregarCliente.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnAgregarCliente.setForeground(new Color(255, 255, 255));
        btnAgregarCliente.setText("AGREGAR");
        btnAgregarCliente.setBorderPainted(false);
        btnAgregarCliente.setFocusable(false);
        jpBotonesCliente.add(btnAgregarCliente);

        btnEditarCliente.setBackground(new Color(249, 170, 51));
        btnEditarCliente.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEditarCliente.setForeground(new Color(255, 255, 255));
        btnEditarCliente.setText("EDITAR");
        btnEditarCliente.setBorderPainted(false);
        btnEditarCliente.setFocusable(false);
        btnEditarCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        jpBotonesCliente.add(btnEditarCliente);

        btnEliminarCliente.setBackground(new Color(102, 0, 0));
        btnEliminarCliente.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEliminarCliente.setForeground(new Color(255, 255, 255));
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.setBorderPainted(false);
        btnEliminarCliente.setFocusable(false);
        jpBotonesCliente.add(btnEliminarCliente);

        jpCliente.add(jpBotonesCliente, java.awt.BorderLayout.SOUTH);

        jpPrincipal.add(jpCliente, "cliente");

        jpProveedor.setLayout(new java.awt.BorderLayout());

        jpFormularioProveedor.setBackground(new Color(74, 101, 114));
        jpFormularioProveedor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        txtIdProveedor.setEditable(false);
        txtIdProveedor.setText("0");
        txtIdProveedor.setEnabled(false);
        txtIdProveedor.setFocusable(false);
        txtIdProveedor.setMinimumSize(new java.awt.Dimension(80, 23));
        txtIdProveedor.setOpaque(true);
        txtIdProveedor.setPreferredSize(new java.awt.Dimension(80, 23));
        txtIdProveedor.setVisible(false);
        jpFormularioProveedor.add(txtIdProveedor);

        lblNitProveedor.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblNitProveedor.setForeground(new Color(255, 255, 255));
        lblNitProveedor.setText("NIT");
        lblNitProveedor.setMinimumSize(new java.awt.Dimension(21, 23));
        lblNitProveedor.setPreferredSize(new java.awt.Dimension(21, 23));
        jpFormularioProveedor.add(lblNitProveedor);

        txtNitProveedor.setColumns(15);
        txtNitProveedor.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtNitProveedor.setToolTipText("");
        txtNitProveedor.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtNitProveedor.setMinimumSize(new java.awt.Dimension(4, 23));
        txtNitProveedor.setPreferredSize(new java.awt.Dimension(199, 23));
        txtNitProveedor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNitProveedorActionPerformed(evt);
            }
        });
        jpFormularioProveedor.add(txtNitProveedor);

        lblNombreProveedor.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblNombreProveedor.setForeground(new Color(255, 255, 255));
        lblNombreProveedor.setText("NOMBRE");
        jpFormularioProveedor.add(lblNombreProveedor);

        txtNombreProveedor.setColumns(15);
        txtNombreProveedor.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtNombreProveedor.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtNombreProveedor.setMinimumSize(new java.awt.Dimension(4, 23));
        txtNombreProveedor.setPreferredSize(new java.awt.Dimension(199, 23));
        txtNombreProveedor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });
        jpFormularioProveedor.add(txtNombreProveedor);

        lblTelefonoProveedor.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblTelefonoProveedor.setForeground(new Color(255, 255, 255));
        lblTelefonoProveedor.setText("TELEFONO");
        jpFormularioProveedor.add(lblTelefonoProveedor);

        txtTelefonoProveedor.setColumns(15);
        txtTelefonoProveedor.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtTelefonoProveedor.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtTelefonoProveedor.setMinimumSize(new java.awt.Dimension(4, 23));
        txtTelefonoProveedor.setPreferredSize(new java.awt.Dimension(199, 23));
        txtTelefonoProveedor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtTelefonoProveedorActionPerformed(evt);
            }
        });
        jpFormularioProveedor.add(txtTelefonoProveedor);

        lblDireccionProveedor.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblDireccionProveedor.setForeground(new Color(255, 255, 255));
        lblDireccionProveedor.setText("DIRECCION");
        jpFormularioProveedor.add(lblDireccionProveedor);

        txtDireccionProveedor.setColumns(15);
        txtDireccionProveedor.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtDireccionProveedor.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtDireccionProveedor.setMinimumSize(new java.awt.Dimension(4, 23));
        txtDireccionProveedor.setPreferredSize(new java.awt.Dimension(199, 23));
        txtDireccionProveedor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtDireccionProveedorActionPerformed(evt);
            }
        });
        jpFormularioProveedor.add(txtDireccionProveedor);

        lblRazonSocialProveedor.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblRazonSocialProveedor.setForeground(new Color(255, 255, 255));
        lblRazonSocialProveedor.setText("RAZON SOCIAL");
        jpFormularioProveedor.add(lblRazonSocialProveedor);

        txtRazonSocialProveedor.setColumns(15);
        txtRazonSocialProveedor.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtRazonSocialProveedor.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtRazonSocialProveedor.setMinimumSize(new java.awt.Dimension(4, 23));
        txtRazonSocialProveedor.setPreferredSize(new java.awt.Dimension(199, 23));
        jpFormularioProveedor.add(txtRazonSocialProveedor);

        jpProveedor.add(jpFormularioProveedor, java.awt.BorderLayout.NORTH);

        jtTablaProveedor.getTableHeader().setFont(new Font("Montserrat", 1, 12));
        jtTablaProveedor.setModel(new DefaultTableModel(
                null,
                new String [] {
                        "ID","NIT", "NOMBRE", "TELEFONO", "DIRECCION", "RAZON SOCIAL"
                }
        ));
        jtTablaProveedor.getTableHeader().setResizingAllowed(false);
        jtTablaProveedor.getTableHeader().setReorderingAllowed(false);
        jspTablaProveedor.setViewportView(jtTablaProveedor);

        jpProveedor.add(jspTablaProveedor, java.awt.BorderLayout.CENTER);

        jpBotonesProveedor.setBackground(new Color(74, 101, 114));
        jpBotonesProveedor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 15));

        btnAgregarProveedor.setBackground(new Color(0, 102, 51));
        btnAgregarProveedor.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnAgregarProveedor.setForeground(new Color(255, 255, 255));
        btnAgregarProveedor.setText("AGREGAR");
        btnAgregarProveedor.setBorderPainted(false);
        btnAgregarProveedor.setFocusable(false);
        jpBotonesProveedor.add(btnAgregarProveedor);

        btnEditarProveedor.setBackground(new Color(249, 170, 51));
        btnEditarProveedor.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEditarProveedor.setForeground(new Color(255, 255, 255));
        btnEditarProveedor.setText("EDITAR");
        btnEditarProveedor.setBorderPainted(false);
        btnEditarProveedor.setFocusable(false);
        btnEditarProveedor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEditarProveedorActionPerformed(evt);
            }
        });
        jpBotonesProveedor.add(btnEditarProveedor);

        btnEliminarProveedor.setBackground(new Color(102, 0, 0));
        btnEliminarProveedor.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEliminarProveedor.setForeground(new Color(255, 255, 255));
        btnEliminarProveedor.setText("ELIMINAR");
        btnEliminarProveedor.setBorderPainted(false);
        btnEliminarProveedor.setFocusable(false);
        jpBotonesProveedor.add(btnEliminarProveedor);

        jpProveedor.add(jpBotonesProveedor, java.awt.BorderLayout.SOUTH);

        jpPrincipal.add(jpProveedor, "proveedor");

        jpInventario.setLayout(new java.awt.BorderLayout());

        jpFormularioInventario.setBackground(new Color(74, 101, 114));
        jpFormularioInventario.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        txtIdProducto.setEditable(false);
        txtIdProducto.setText("0");
        txtIdProducto.setEnabled(false);
        txtIdProducto.setFocusable(false);
        txtIdProducto.setMinimumSize(new java.awt.Dimension(80, 23));
        txtIdProducto.setOpaque(true);
        txtIdProducto.setPreferredSize(new java.awt.Dimension(80, 23));
        txtIdProducto.setVisible(false);
        jpFormularioInventario.add(txtIdProducto);

        lblCodigoProducto.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblCodigoProducto.setForeground(new Color(255, 255, 255));
        lblCodigoProducto.setText("CODIGO");
        jpFormularioInventario.add(lblCodigoProducto);

        txtCodigoProducto.setColumns(10);
        txtCodigoProducto.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtCodigoProducto.setToolTipText("");
        txtCodigoProducto.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtCodigoProducto.setMinimumSize(new java.awt.Dimension(4, 23));
        txtCodigoProducto.setPreferredSize(new java.awt.Dimension(134, 23));
        txtCodigoProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        jpFormularioInventario.add(txtCodigoProducto);

        lblNombreProducto.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblNombreProducto.setForeground(new Color(255, 255, 255));
        lblNombreProducto.setText("NOMBRE");
        jpFormularioInventario.add(lblNombreProducto);

        txtNombreProducto.setColumns(10);
        txtNombreProducto.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtNombreProducto.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtNombreProducto.setMinimumSize(new java.awt.Dimension(4, 23));
        txtNombreProducto.setPreferredSize(new java.awt.Dimension(134, 23));
        txtNombreProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        jpFormularioInventario.add(txtNombreProducto);

        lblPrecioCompraProducto.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblPrecioCompraProducto.setForeground(new Color(255, 255, 255));
        lblPrecioCompraProducto.setText("PRECIO COMPRA");
        jpFormularioInventario.add(lblPrecioCompraProducto);

        txtPrecioCompraProducto.setColumns(10);
        txtPrecioCompraProducto.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtPrecioCompraProducto.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtPrecioCompraProducto.setEnabled(false);
        txtPrecioCompraProducto.setMinimumSize(new java.awt.Dimension(4, 23));
        txtPrecioCompraProducto.setPreferredSize(new java.awt.Dimension(134, 23));
        txtPrecioCompraProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPrecioCompraProductoActionPerformed(evt);
            }
        });
        jpFormularioInventario.add(txtPrecioCompraProducto);

        lblPrecioVentaProducto.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblPrecioVentaProducto.setForeground(new Color(255, 255, 255));
        lblPrecioVentaProducto.setText("PRECIO VENTA");
        jpFormularioInventario.add(lblPrecioVentaProducto);

        txtPrecioVentaProducto.setColumns(10);
        txtPrecioVentaProducto.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtPrecioVentaProducto.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtPrecioVentaProducto.setMinimumSize(new java.awt.Dimension(4, 23));
        txtPrecioVentaProducto.setPreferredSize(new java.awt.Dimension(134, 23));
        txtPrecioVentaProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPrecioVentaProductoActionPerformed(evt);
            }
        });
        jpFormularioInventario.add(txtPrecioVentaProducto);

        lblStockProducto.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblStockProducto.setForeground(new Color(255, 255, 255));
        lblStockProducto.setText("STOCK");
        jpFormularioInventario.add(lblStockProducto);

        txtStockProducto.setColumns(10);
        txtStockProducto.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtStockProducto.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtStockProducto.setMinimumSize(new java.awt.Dimension(4, 23));
        txtStockProducto.setPreferredSize(new java.awt.Dimension(134, 23));
        jpFormularioInventario.add(txtStockProducto);

        lblProveedorInventario.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblProveedorInventario.setForeground(new Color(255, 255, 255));
        lblProveedorInventario.setText("PROVEEDOR");
        jpFormularioInventario.add(lblProveedorInventario);

        txtProveedorProducto.setColumns(10);
        txtProveedorProducto.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtProveedorProducto.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtProveedorProducto.setEnabled(false);
        txtProveedorProducto.setMinimumSize(new java.awt.Dimension(4, 23));
        txtProveedorProducto.setPreferredSize(new java.awt.Dimension(134, 23));
        jpFormularioInventario.add(txtProveedorProducto);

        jpInventario.add(jpFormularioInventario, java.awt.BorderLayout.NORTH);

        jtTablaInventario.getTableHeader().setFont(new Font("Montserrat", 1, 12));
        jtTablaInventario.setModel(new DefaultTableModel(
                null,
                new String [] {
                        "ID","CODIGO", "NOMBRE", "PRECIO COMPRA", "PRECIO VENTA", "STOCK", "PROVEEDOR"
                }
        ));
        jtTablaInventario.getTableHeader().setResizingAllowed(false);
        jtTablaInventario.getTableHeader().setReorderingAllowed(false);
        jspTablaInventario.setViewportView(jtTablaInventario);

        jpInventario.add(jspTablaInventario, java.awt.BorderLayout.CENTER);

        jpBotonesInventario.setBackground(new Color(74, 101, 114));
        jpBotonesInventario.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 15));

        btnEditarProducto.setBackground(new Color(249, 170, 51));
        btnEditarProducto.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEditarProducto.setForeground(new Color(255, 255, 255));
        btnEditarProducto.setText("EDITAR");
        btnEditarProducto.setBorderPainted(false);
        btnEditarProducto.setFocusable(false);
        btnEditarProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });
        jpBotonesInventario.add(btnEditarProducto);

        btnEliminarProducto.setBackground(new Color(102, 0, 0));
        btnEliminarProducto.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEliminarProducto.setForeground(new Color(255, 255, 255));
        btnEliminarProducto.setText("ELIMINAR");
        btnEliminarProducto.setBorderPainted(false);
        btnEliminarProducto.setFocusable(false);
        jpBotonesInventario.add(btnEliminarProducto);

        jpInventario.add(jpBotonesInventario, java.awt.BorderLayout.SOUTH);

        jpPrincipal.add(jpInventario, "inventario");

        jpComprar.setLayout(new java.awt.BorderLayout());

        jpFormularioComprar.setBackground(new Color(74, 101, 114));
        jpFormularioComprar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblCodigoCompra.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblCodigoCompra.setForeground(new Color(255, 255, 255));
        lblCodigoCompra.setText("CODIGO");
        jpFormularioComprar.add(lblCodigoCompra);

        txtCodigoComprar.setColumns(10);
        txtCodigoComprar.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtCodigoComprar.setToolTipText("");
        txtCodigoComprar.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtCodigoComprar.setMinimumSize(new java.awt.Dimension(4, 23));
        txtCodigoComprar.setPreferredSize(new java.awt.Dimension(134, 23));
        txtCodigoComprar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtCodigoComprarActionPerformed(evt);
            }
        });
        jpFormularioComprar.add(txtCodigoComprar);

        lblNombreCompra.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblNombreCompra.setForeground(new Color(255, 255, 255));
        lblNombreCompra.setText("NOMBRE");
        jpFormularioComprar.add(lblNombreCompra);

        txtNombreComprar.setColumns(10);
        txtNombreComprar.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtNombreComprar.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtNombreComprar.setMinimumSize(new java.awt.Dimension(4, 23));
        txtNombreComprar.setPreferredSize(new java.awt.Dimension(134, 23));
        txtNombreComprar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNombreComprarActionPerformed(evt);
            }
        });
        jpFormularioComprar.add(txtNombreComprar);

        lblPrecioCompraComprar.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblPrecioCompraComprar.setForeground(new Color(255, 255, 255));
        lblPrecioCompraComprar.setText("PRECIO COMPRA");
        jpFormularioComprar.add(lblPrecioCompraComprar);

        txtPrecioCompraComprar.setColumns(10);
        txtPrecioCompraComprar.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtPrecioCompraComprar.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtPrecioCompraComprar.setMinimumSize(new java.awt.Dimension(4, 23));
        txtPrecioCompraComprar.setPreferredSize(new java.awt.Dimension(134, 23));
        txtPrecioCompraComprar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPrecioCompraComprarActionPerformed(evt);
            }
        });
        jpFormularioComprar.add(txtPrecioCompraComprar);

        lblPrecioVentaComprar.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblPrecioVentaComprar.setForeground(new Color(255, 255, 255));
        lblPrecioVentaComprar.setText("PRECIO VENTA");
        jpFormularioComprar.add(lblPrecioVentaComprar);

        txtPrecioVentaComprar.setColumns(10);
        txtPrecioVentaComprar.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtPrecioVentaComprar.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtPrecioVentaComprar.setEnabled(false);
        txtPrecioVentaComprar.setMinimumSize(new java.awt.Dimension(4, 23));
        txtPrecioVentaComprar.setPreferredSize(new java.awt.Dimension(134, 23));
        txtPrecioVentaComprar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPrecioVentaComprarActionPerformed(evt);
            }
        });
        jpFormularioComprar.add(txtPrecioVentaComprar);

        lblStockComprar.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblStockComprar.setForeground(new Color(255, 255, 255));
        lblStockComprar.setText("STOCK");
        jpFormularioComprar.add(lblStockComprar);

        txtStockComprar.setColumns(10);
        txtStockComprar.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtStockComprar.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtStockComprar.setMinimumSize(new java.awt.Dimension(4, 23));
        txtStockComprar.setPreferredSize(new java.awt.Dimension(134, 23));
        jpFormularioComprar.add(txtStockComprar);

        lblProveedorComprar.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblProveedorComprar.setForeground(new Color(255, 255, 255));
        lblProveedorComprar.setText("PROVEEDOR");
        jpFormularioComprar.add(lblProveedorComprar);

        jcbProveedorComprar.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        jcbProveedorComprar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Real Madrid", "Item 2", "Item 3", "Item 4" }));
        jcbProveedorComprar.setToolTipText("");
        jcbProveedorComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbProveedorComprar.setMinimumSize(new java.awt.Dimension(134, 23));
        jcbProveedorComprar.setPreferredSize(new java.awt.Dimension(134, 23));
        jpFormularioComprar.add(jcbProveedorComprar);

        jpComprar.add(jpFormularioComprar, java.awt.BorderLayout.NORTH);

        jtTablaComprar.getTableHeader().setFont(new Font("Montserrat", 1, 12));
        jtTablaComprar.setModel(new DefaultTableModel(
                null,
                new String [] {
                        "ID","CODIGO", "NOMBRE", "PRECIO COMPRA", "PRECIO VENTA", "STOCK"
                }
        ));
        jtTablaComprar.getTableHeader().setResizingAllowed(false);
        jtTablaComprar.getTableHeader().setReorderingAllowed(false);
        jspTablaComprar.setViewportView(jtTablaComprar);

        jpComprar.add(jspTablaComprar, java.awt.BorderLayout.CENTER);

        jpInferiorComprar.setBackground(new Color(74, 101, 114));
        jpInferiorComprar.setLayout(new java.awt.BorderLayout());

        jpBotonesComprar.setBackground(new Color(74, 101, 114));
        jpBotonesComprar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 15));

        btnAgregarCompra.setBackground(new Color(0, 102, 51));
        btnAgregarCompra.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnAgregarCompra.setForeground(new Color(255, 255, 255));
        btnAgregarCompra.setText("AGREGAR");
        btnAgregarCompra.setBorderPainted(false);
        btnAgregarCompra.setFocusable(false);
        btnAgregarCompra.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnAgregarCompraActionPerformed(evt);
            }
        });
        jpBotonesComprar.add(btnAgregarCompra);

        btnRealizarCompra.setBackground(new Color(249, 170, 51));
        btnRealizarCompra.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnRealizarCompra.setForeground(new Color(255, 255, 255));
        btnRealizarCompra.setText("COMPRAR");
        btnRealizarCompra.setBorderPainted(false);
        btnRealizarCompra.setFocusable(false);
        btnRealizarCompra.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRealizarCompraActionPerformed(evt);
            }
        });
        jpBotonesComprar.add(btnRealizarCompra);

        btnEliminarCompra.setBackground(new Color(102, 0, 0));
        btnEliminarCompra.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEliminarCompra.setForeground(new Color(255, 255, 255));
        btnEliminarCompra.setText("ELIMINAR");
        btnEliminarCompra.setBorderPainted(false);
        btnEliminarCompra.setFocusable(false);
        btnEliminarCompra.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEliminarCompraActionPerformed(evt);
            }
        });
        jpBotonesComprar.add(btnEliminarCompra);

        jpInferiorComprar.add(jpBotonesComprar, java.awt.BorderLayout.CENTER);

        jpValoresTotales.setBackground(new Color(204, 210, 220));
        jpValoresTotales.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblProductosTotalesComprar.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblProductosTotalesComprar.setText("PRODUCTO TOTALES : 0");
        jpValoresTotales.add(lblProductosTotalesComprar);

        lblPrecioTotalComprar.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblPrecioTotalComprar.setText("PRECIO TOTAL : 0");
        jpValoresTotales.add(lblPrecioTotalComprar);

        jpInferiorComprar.add(jpValoresTotales, java.awt.BorderLayout.NORTH);

        jpComprar.add(jpInferiorComprar, java.awt.BorderLayout.SOUTH);

        jpPrincipal.add(jpComprar, "comprar");

        jpVender.setLayout(new java.awt.BorderLayout());

        jpFormularioComprar1.setBackground(new Color(74, 101, 114));
        jpFormularioComprar1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblProductoVender.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblProductoVender.setForeground(new Color(255, 255, 255));
        lblProductoVender.setText("PRODUCTO");
        jpFormularioComprar1.add(lblProductoVender);

        jcbProductoVender.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        jcbProductoVender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbProductoVender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbProductoVender.setMinimumSize(new java.awt.Dimension(160, 23));
        jcbProductoVender.setPreferredSize(new java.awt.Dimension(160, 23));
        jpFormularioComprar1.add(jcbProductoVender);

        lblStockVender.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblStockVender.setForeground(new Color(255, 255, 255));
        lblStockVender.setText("STOCK");
        jpFormularioComprar1.add(lblStockVender);

        txtStockVender.setColumns(12);
        txtStockVender.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        txtStockVender.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtStockVender.setMinimumSize(new java.awt.Dimension(4, 23));
        txtStockVender.setPreferredSize(new java.awt.Dimension(160, 23));
        txtStockVender.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtStockVenderActionPerformed(evt);
            }
        });
        jpFormularioComprar1.add(txtStockVender);

        lblClienteVender.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblClienteVender.setForeground(new Color(255, 255, 255));
        lblClienteVender.setText("CLIENTE");
        jpFormularioComprar1.add(lblClienteVender);

        jcbClienteVender.setFont(new Font("Montserrat", 0, 12)); // NOI18N
        jcbClienteVender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbClienteVender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbClienteVender.setMinimumSize(new java.awt.Dimension(160, 23));
        jcbClienteVender.setName(""); // NOI18N
        jcbClienteVender.setPreferredSize(new java.awt.Dimension(160, 23));
        jpFormularioComprar1.add(jcbClienteVender);

        jpVender.add(jpFormularioComprar1, java.awt.BorderLayout.NORTH);

        jtTablaVender.getTableHeader().setFont(new Font("Montserrat", 1, 12));
        jtTablaVender.setModel(new DefaultTableModel(
                null,
                new String [] {
                        "ID","PRODUCTO", "STOCK", "PRECIO"
                }
        ));
        jtTablaVender.getTableHeader().setResizingAllowed(false);
        jtTablaVender.getTableHeader().setReorderingAllowed(false);
        jspTablaVender.setViewportView(jtTablaVender);

        jpVender.add(jspTablaVender, java.awt.BorderLayout.CENTER);

        jpInferiorVender.setBackground(new Color(74, 101, 114));
        jpInferiorVender.setLayout(new java.awt.BorderLayout());

        jpBotonesVender.setBackground(new Color(74, 101, 114));
        jpBotonesVender.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 15));

        btnAgregarVenta.setBackground(new Color(0, 102, 51));
        btnAgregarVenta.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnAgregarVenta.setForeground(new Color(255, 255, 255));
        btnAgregarVenta.setText("AGREGAR");
        btnAgregarVenta.setBorderPainted(false);
        btnAgregarVenta.setFocusable(false);
        btnAgregarVenta.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnAgregarVentaActionPerformed(evt);
            }
        });
        jpBotonesVender.add(btnAgregarVenta);

        btnRealizarVenta.setBackground(new Color(249, 170, 51));
        btnRealizarVenta.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnRealizarVenta.setForeground(new Color(255, 255, 255));
        btnRealizarVenta.setText("VENDER");
        btnRealizarVenta.setBorderPainted(false);
        btnRealizarVenta.setFocusable(false);
        btnRealizarVenta.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRealizarVentaActionPerformed(evt);
            }
        });
        jpBotonesVender.add(btnRealizarVenta);

        btnEliminarVenta.setBackground(new Color(102, 0, 0));
        btnEliminarVenta.setFont(new Font("Montserrat", 1, 14)); // NOI18N
        btnEliminarVenta.setForeground(new Color(255, 255, 255));
        btnEliminarVenta.setText("ELIMINAR");
        btnEliminarVenta.setBorderPainted(false);
        btnEliminarVenta.setFocusable(false);
        btnEliminarVenta.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEliminarVentaActionPerformed(evt);
            }
        });
        jpBotonesVender.add(btnEliminarVenta);

        jpInferiorVender.add(jpBotonesVender, java.awt.BorderLayout.CENTER);

        jpValoresTotalesVenta.setBackground(new Color(204, 210, 220));
        jpValoresTotalesVenta.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblProductosTotalesVender.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblProductosTotalesVender.setText("PRODUCTO TOTALES : 0");
        jpValoresTotalesVenta.add(lblProductosTotalesVender);

        lblPrecioTotalVender.setFont(new Font("Montserrat", 1, 12)); // NOI18N
        lblPrecioTotalVender.setText("PRECIO TOTAL : 0");
        jpValoresTotalesVenta.add(lblPrecioTotalVender);

        jpInferiorVender.add(jpValoresTotalesVenta, java.awt.BorderLayout.NORTH);

        jpVender.add(jpInferiorVender, java.awt.BorderLayout.SOUTH);

        jpPrincipal.add(jpVender, "vender");

        jpCompras.setLayout(new java.awt.BorderLayout());

        jpSuperiorCompras.setBackground(new Color(74, 101, 114));
        jpSuperiorCompras.setPreferredSize(new java.awt.Dimension(1307, 53));
        jpSuperiorCompras.add(filler9);

        jpCompras.add(jpSuperiorCompras, java.awt.BorderLayout.NORTH);

        jtTablaCompras.getTableHeader().setFont(new Font("Montserrat", 1, 12));
        jtTablaCompras.setModel(new DefaultTableModel(
                null,
                new String [] {
                        "ID","PRODUCTOS", "PRECIO", "CANTIDAD", "PRECIO TOTAL", "CANTIDAD TOTAL", "PROVEEDOR"
                }
        ));
        jtTablaCompras.getTableHeader().setResizingAllowed(false);
        jtTablaCompras.getTableHeader().setReorderingAllowed(false);
        jspTablaCompras.setViewportView(jtTablaCompras);

        jpCompras.add(jspTablaCompras, java.awt.BorderLayout.CENTER);

        jpInferiorCompras.setBackground(new Color(74, 101, 114));
        jpInferiorCompras.setPreferredSize(new java.awt.Dimension(1307, 53));
        jpInferiorCompras.setRequestFocusEnabled(false);
        jpInferiorCompras.add(filler10);

        jpCompras.add(jpInferiorCompras, java.awt.BorderLayout.PAGE_END);

        jpPrincipal.add(jpCompras, "compras");

        jpVentas.setLayout(new java.awt.BorderLayout());

        jpSuperiorVentas.setBackground(new Color(74, 101, 114));
        jpSuperiorVentas.setPreferredSize(new java.awt.Dimension(1307, 53));
        jpSuperiorVentas.add(filler11);

        jpVentas.add(jpSuperiorVentas, java.awt.BorderLayout.NORTH);

        jtTablaVentas.getTableHeader().setFont(new Font("Montserrat", 1, 12));
        jtTablaVentas.setModel(new DefaultTableModel(
                null,
                new String [] {
                        "ID","PRODUCTOS", "PRECIO", "CANTIDAD", "PRECIO TOTAL", "CANTIDAD TOTAL", "CLIENTE"
                        + ""
                }
        ));
        jtTablaVentas.getTableHeader().setResizingAllowed(false);
        jtTablaVentas.getTableHeader().setReorderingAllowed(false);
        jspTablaVentas.setViewportView(jtTablaVentas);

        jpVentas.add(jspTablaVentas, java.awt.BorderLayout.CENTER);

        jpInferiorVentas.setBackground(new Color(74, 101, 114));
        jpInferiorVentas.setPreferredSize(new java.awt.Dimension(1307, 53));
        jpInferiorVentas.setRequestFocusEnabled(false);
        jpInferiorVentas.add(filler12);

        jpVentas.add(jpInferiorVentas, java.awt.BorderLayout.PAGE_END);

        jpPrincipal.add(jpVentas, "ventas");

        getContentPane().add(jpPrincipal, java.awt.BorderLayout.CENTER);

        jpEncabezado.setBackground(new Color(35, 47, 52));
        jpEncabezado.setForeground(new Color(255, 255, 255));
        jpEncabezado.setFont(new Font("Montserrat", 0, 18)); // NOI18N
        jpEncabezado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 40, 10));

        lblIcono.setIcon(new ImageIcon(getClass().getResource("/carrito-de-supermercado.png"))); // NOI18N
        jpEncabezado.add(lblIcono);

        lblTitulo.setFont(new Font("Montserrat", 1, 28)); // NOI18N
        lblTitulo.setForeground(new Color(255, 255, 255));
        lblTitulo.setText("GESTION SUPERMERCADO UNIVALLE");
        jpEncabezado.add(lblTitulo);

        getContentPane().add(jpEncabezado, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>

    private void btnClientesActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnProveedoresActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnVentasActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNitClienteActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNombreClienteActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtTelefonoClienteActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtDireccionClienteActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnClientesMouseEntered(MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btnEditarClienteActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNitProveedorActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNombreProveedorActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtTelefonoProveedorActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtDireccionProveedorActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnEditarProveedorActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnEditarProductoActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnVenderActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnComprarActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtCodigoComprarActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNombreComprarActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPrecioCompraComprarActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPrecioVentaComprarActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAgregarCompraActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnEliminarCompraActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnRealizarCompraActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtStockVenderActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAgregarVentaActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnRealizarVentaActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnEliminarVentaActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPrecioVentaProductoActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPrecioCompraProductoActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNombreProductoActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtCodigoProductoActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    //==========|ActionListener Botones Formulario|==========//
    //=====|Cliente|=====//
    public void addBtnAgregarClienteListener(ActionListener listenControles)
    {
        btnAgregarCliente.addActionListener(listenControles);
    }

    public void addBtnEditarClienteListener(ActionListener listenControles)
    {
        btnEditarCliente.addActionListener(listenControles);
    }

    public void addBtnEliminarClienteListener(ActionListener listenControles)
    {
        btnEliminarCliente.addActionListener(listenControles);
    }

    //=====|Proveedor|=====//
    public void addBtnAgregarProveedorListener(ActionListener listenControles)
    {
        btnAgregarProveedor.addActionListener(listenControles);
    }

    public void addBtnEditarProveedorListener(ActionListener listenControles)
    {
        btnEditarProveedor.addActionListener(listenControles);
    }

    public void addBtnEliminarProveedorListener(ActionListener listenControles)
    {
        btnEliminarProveedor.addActionListener(listenControles);
    }

    //=====|Producto|=====//
    public void addBtnEditarProductoListener(ActionListener listenControles)
    {
        btnEditarProducto.addActionListener(listenControles);
    }

    public void addBtnEliminarProductoListener(ActionListener listenControles)
    {
        btnEliminarProducto.addActionListener(listenControles);
    }

    //=====|Comprar|=====//
    public void addBtnAgregarCompraListener(ActionListener listenControles)
    {
        btnAgregarCompra.addActionListener(listenControles);
    }

    public void addBtnRealizarCompraListener(ActionListener listenControles)
    {
        btnRealizarCompra.addActionListener(listenControles);
    }

    public void addBtnEliminarCompraListener(ActionListener listenControles)
    {
        btnEliminarCompra.addActionListener(listenControles);
    }

    //=====|Vender|=====//
    public void addBtnAgregarVentaListener(ActionListener listenControles)
    {
        btnAgregarVenta.addActionListener(listenControles);
    }

    public void addBtnRealizarVentaListener(ActionListener listenControles)
    {
        btnRealizarVenta.addActionListener(listenControles);
    }

    public void addBtnEliminarVentaListener(ActionListener listenControles)
    {
        btnEliminarVenta.addActionListener(listenControles);
    }

    //=====|Todos|=====//
    public void addBotonesFormularioListener(MouseAdapter listenControles)
    {
        btnAgregarCliente.addMouseListener(listenControles);
        btnEditarCliente.addMouseListener(listenControles);
        btnEliminarCliente.addMouseListener(listenControles);
        btnAgregarProveedor.addMouseListener(listenControles);
        btnEditarProveedor.addMouseListener(listenControles);
        btnEliminarProveedor.addMouseListener(listenControles);
        btnEditarProducto.addMouseListener(listenControles);
        btnEliminarProducto.addMouseListener(listenControles);
        btnAgregarCompra.addMouseListener(listenControles);
        btnRealizarCompra.addMouseListener(listenControles);
        btnEliminarCompra.addMouseListener(listenControles);
        btnAgregarVenta.addMouseListener(listenControles);
        btnRealizarVenta.addMouseListener(listenControles);
        btnEliminarVenta.addMouseListener(listenControles);
    }

    //==========|ActionListener Botones Principal|==========//
    //=====|Cliente|=====//
    public void addBotonesPrincipalListener(ActionListener listenControles)
    {
        btnClientes.addActionListener(listenControles);
        btnProveedores.addActionListener(listenControles);
        btnInventario.addActionListener(listenControles);
        btnComprar.addActionListener(listenControles);
        btnVender.addActionListener(listenControles);
        btnCompras.addActionListener(listenControles);
        btnVentas.addActionListener(listenControles);
    }

    public void addBotonesPrincipalColorListener(MouseAdapter listenControles)
    {
        btnClientes.addMouseListener(listenControles);
        btnProveedores.addMouseListener(listenControles);
        btnInventario.addMouseListener(listenControles);
        btnComprar.addMouseListener(listenControles);
        btnVender.addMouseListener(listenControles);
        btnCompras.addMouseListener(listenControles);
        btnVentas.addMouseListener(listenControles);
    }

    //==========|ActionListener Tablas|==========//
    //=====|Cliente|=====//
    public void addTablaClienteListener(MouseAdapter listenControles)
    {
        jtTablaCliente.addMouseListener(listenControles);
    }

    //=====|Proveedor|=====//
    public void addTablaProveedorListener(MouseAdapter listenControles)
    {
        jtTablaProveedor.addMouseListener(listenControles);
    }

    //=====|Producto|=====//
    public void addTablaInventarioListener(MouseAdapter listenControles)
    {
        jtTablaInventario.addMouseListener(listenControles);
    }

    //=====|Comprar|=====//
    public void addTablaComprarListener(MouseAdapter listenControles)
    {
        jtTablaComprar.addMouseListener(listenControles);
    }

    //=====|Vender|=====//
    public void addTablaVenderListener(MouseAdapter listenControles)
    {
        jtTablaVender.addMouseListener(listenControles);
    }

    //==========|Cambio de paginas|==========//
    public void pagInicial()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "inicial");
    }

    public void pagCliente()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "cliente");
    }

    public void pagProveedor()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "proveedor");
    }

    public void pagInventario()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "inventario");
    }

    public void pagComprar()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "comprar");
    }

    public void pagVender()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "vender");
    }

    public void pagCompras()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "compras");
    }

    public void pagVentas()
    {
        CardLayout a = (CardLayout)jpPrincipal.getLayout();
        a.show(jpPrincipal, "ventas");
    }

    //==========|Listener paginas|==========//
    class CambiarPaginaListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getActionCommand().equalsIgnoreCase("CLIENTES"))
            {
                pagCliente();
            }
            if (e.getActionCommand().equalsIgnoreCase("PROVEEDORES"))
            {
                pagProveedor();
            }
            if (e.getActionCommand().equalsIgnoreCase("INVENTARIO"))
            {
                pagInventario();
            }
            if (e.getActionCommand().equalsIgnoreCase("COMPRAR"))
            {
                pagComprar();
            }
            if (e.getActionCommand().equalsIgnoreCase("VENDER"))
            {
                pagVender();
            }
            if (e.getActionCommand().equalsIgnoreCase("COMPRAS"))
            {
                pagCompras();
            }
            if (e.getActionCommand().equalsIgnoreCase("VENTAS"))
            {
                pagVentas();
            }
        }
    }

    //==========|Listener Color Botones Principales|==========//
    class ManejadoraDeMouse extends MouseAdapter
    {
        @Override
        public void mouseEntered(MouseEvent arg0)
        {
            JButton auxBoton = (JButton)arg0.getSource();
            auxBoton.setForeground(new Color(249,170,51));
            if(auxBoton.getActionCommand().equalsIgnoreCase("CLIENTES"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/clienteSeleccionado.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("PROVEEDORES"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/proveedorSeleccionado.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("INVENTARIO"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/inventarioSeleccionado.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("COMPRAR"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/compraSeleccionada.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("VENDER"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/ventaSeleccionada.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("COMPRAS"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/facturaSeleccionada.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("VENTAS"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/factura.png")));
            }
        }

        @Override
        public void mouseExited(MouseEvent e)
        {
            JButton auxBoton = (JButton)e.getSource();
            auxBoton.setForeground(Color.white);
            if(auxBoton.getActionCommand().equalsIgnoreCase("CLIENTES"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/cliente.png")));

            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("PROVEEDORES"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/proveedor.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("INVENTARIO"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/inventario.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("COMPRAR"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/compra.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("VENDER"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/venta.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("COMPRAS"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/factura.png")));
            }
            if(auxBoton.getActionCommand().equalsIgnoreCase("VENTAS"))
            {
                auxBoton.setIcon(new ImageIcon(getClass().getResource("/factura.png")));
            }
        }
    }

    //==========|Listener Color Botones Formulario|==========//
    class BotonesFormularioListener extends MouseAdapter
    {
        @Override
        public void mouseEntered(MouseEvent arg0)
        {
            JButton auxBoton = (JButton)arg0.getSource();
            if (auxBoton.getActionCommand().equalsIgnoreCase("AGREGAR"))
            {
                auxBoton.setBackground(new Color(0,102,51).brighter());
            }
            if (auxBoton.getActionCommand().equalsIgnoreCase("EDITAR") || auxBoton.getActionCommand().equalsIgnoreCase("COMPRAR") || auxBoton.getActionCommand().equalsIgnoreCase("VENDER"))
            {
                auxBoton.setBackground(new Color(249,170,51).brighter());
            }
            if (auxBoton.getActionCommand().equalsIgnoreCase("ELIMINAR"))
            {
                auxBoton.setBackground(new Color(102,0,0).brighter());
            }
        }

        @Override
        public void mouseExited(MouseEvent e)
        {
            JButton auxBoton = (JButton)e.getSource();
            if (auxBoton.getActionCommand().equalsIgnoreCase("AGREGAR"))
            {
                auxBoton.setBackground(new Color(0,102,51));
            }
            if (auxBoton.getActionCommand().equalsIgnoreCase("EDITAR") || auxBoton.getActionCommand().equalsIgnoreCase("COMPRAR") || auxBoton.getActionCommand().equalsIgnoreCase("VENDER"))
            {
                auxBoton.setBackground(new Color(249,170,51));
            }
            if (auxBoton.getActionCommand().equalsIgnoreCase("ELIMINAR"))
            {
                auxBoton.setBackground(new Color(102,0,0));
            }
        }
    }

    //==========|Listener Tablas|==========//
    //=====|Todos|=====//
    class TablaClienteListener extends MouseAdapter
    {
        @Override
        public void mouseClicked(MouseEvent e)
        {
            JTable tabla = (JTable)e.getSource();
            int fila = tabla.getSelectedRow();
            if(fila == -1)
            {
                setIdCliente("0");
                setNitCliente("");
                setNombreCliente("");
                setTelefonoCliente("");
                setDireccionCliente("");
            }
            else
            {
                setIdCliente(String.valueOf(tabla.getValueAt(tabla.getSelectedRow() , 0)));
                setNitCliente(String.valueOf(tabla.getValueAt(tabla.getSelectedRow() , 1)));
                setNombreCliente(String.valueOf(tabla.getValueAt(tabla.getSelectedRow() , 2)));
                setTelefonoCliente(String.valueOf(tabla.getValueAt(tabla.getSelectedRow() , 3)));
                setDireccionCliente(String.valueOf(tabla.getValueAt(tabla.getSelectedRow() , 4)));
            }

        }
    }

    //=====|Cliente|=====//
    public TableModel getModelTablaCliente()
    {
        return jtTablaCliente.getModel();
    }

    public int getFilaSeleccionadaCliente()
    {
        return jtTablaCliente.getSelectedRow();
    }

    public void deseleccionarFilaTablaCliente()
    {
        jtTablaCliente.getSelectionModel().clearSelection();
    }

    //=====|Proveedor|=====//
    public void actualizarTablaProveedor(DefaultTableModel auxModel)
    {
        jtTablaProveedor.setModel(auxModel);
    }

    public void deseleccionarFilaTablaProveedor()
    {
        jtTablaProveedor.getSelectionModel().clearSelection();
    }

    //=====|Producto|=====//
    public void actualizarTablaInventario(DefaultTableModel auxModel)
    {
        jtTablaInventario.setModel(auxModel);
    }

    public void deseleccionarFilaTablaInventario()
    {
        jtTablaInventario.getSelectionModel().clearSelection();
    }

    //=====|Comprar|=====//
    public void actualizarTablaComprar(DefaultTableModel auxModel)
    {
        jtTablaComprar.setModel(auxModel);
    }

    public void deseleccionarFilaTablaComprar()
    {
        jtTablaComprar.getSelectionModel().clearSelection();
    }

    //=====|Vender|=====//
    public void actualizarTablaVender(DefaultTableModel auxModel)
    {
        jtTablaVender.setModel(auxModel);
    }

    public void deseleccionarFilaTablaVender()
    {
        jtTablaVender.getSelectionModel().clearSelection();
    }

    //=====|Compras|=====//
    public void actualizarTablaCompras(DefaultTableModel auxModel)
    {
        jtTablaCompras.setModel(auxModel);
    }

    //=====|Ventas|=====//
    public void actualizarTablaVentas(DefaultTableModel auxModel)
    {
        jtTablaVentas.setModel(auxModel);
    }

    //==========|Setters|==========//
    //=====|Cliente|=====//
    public void setIdCliente(String txt)
    {
        txtIdCliente.setText(txt);
    }

    public void setNitCliente(String txt)
    {
        txtNitCliente.setText(txt);
    }

    public void setNombreCliente(String txt)
    {
        txtNombreCliente.setText(txt);
    }

    public void setTelefonoCliente(String txt)
    {
        txtTelefonoCliente.setText(txt);
    }

    public void setDireccionCliente(String txt)
    {
        txtDireccionCliente.setText(txt);
    }

    //=====|Proveedor|=====//
    public void setIdProveedor(String txt)
    {
        txtIdProveedor.setText(txt);
    }

    public void setNitProveedor(String txt)
    {
        txtNitProveedor.setText(txt);
    }

    public void setNombreProveedor(String txt)
    {
        txtNombreProveedor.setText(txt);
    }

    public void setTelefonoProveedor(String txt)
    {
        txtTelefonoProveedor.setText(txt);
    }

    public void setDireccionProveedor(String txt)
    {
        txtDireccionProveedor.setText(txt);
    }

    public void setRazonSocialProveedor(String txt)
    {
        txtRazonSocialProveedor.setText(txt);
    }

    //=====|Producto|=====//
    public void setIdProducto(String txt)
    {
        txtIdProducto.setText(txt);
    }

    public void setCodigoProducto(String txt)
    {
        txtCodigoProducto.setText(txt);
    }

    public void setNombreProducto(String txt)
    {
        txtNombreProducto.setText(txt);
    }

    public void setPrecioCompraProducto(String txt)
    {
        txtPrecioCompraProducto.setText(txt);
    }

    public void setPrecioVentaProducto(String txt)
    {
        txtPrecioVentaProducto.setText(txt);
    }

    public void setStockProducto(String txt)
    {
        txtStockProducto.setText(txt);
    }

    public void setProveedorProducto(String txt)
    {
        txtProveedorProducto.setText(txt);
    }

    //=====|Comprar|=====//
    public void setCodigoComprar(String txt)
    {
        txtCodigoComprar.setText(txt);
    }

    public void setNombreComprar(String txt)
    {
        txtNombreComprar.setText(txt);
    }

    public void setPrecioCompraComprar(String txt)
    {
        txtPrecioCompraComprar.setText(txt);
    }

    public void setPrecioVentaComprar(String txt)
    {
        txtPrecioVentaProducto.setText(txt);
    }

    public void setStockComprar(String txt)
    {
        txtStockComprar.setText(txt);
    }

    public void setPrecioTotalComprar(String txt)
    {
        lblPrecioTotalComprar.setText("PRECIO TOTAL : " + txt);
    }

    public void setProductosTotalesComprar(String txt)
    {
        lblProductosTotalesComprar.setText("PRODUCTO TOTALES : " + txt);
    }

    //=====|Vender|=====//
    public void setNullProductoVender()
    {
        jcbProductoVender.setSelectedItem(null);
    }

    public void setStockVender(String txt)
    {
        txtStockVender.setText(txt);
    }

    public void setNullClienteVender()
    {
        jcbClienteVender.setSelectedItem(null);
    }

    public void setPrecioTotalVender(String txt)
    {
        lblPrecioTotalVender.setText("PRECIO TOTAL : " + txt);
    }

    public void setProductosTotalesVender(String txt)
    {
        lblProductosTotalesVender.setText("PRODUCTO TOTALES : " + txt);
    }


    //==========|Getters|==========//
    //=====|Cliente|=====//
    public String getIdCliente()
    {
        return txtIdCliente.getText();
    }

    public String getNitCliente()
    {
        return txtNitCliente.getText();
    }

    public String getNombreCliente()
    {
        return txtNombreCliente.getText();
    }

    public String getTelefonoCliente()
    {
        return txtTelefonoCliente.getText();
    }

    public String getDireccionCliente()
    {
        return txtDireccionCliente.getText();
    }

    //=====|Proveedor|=====//
    public String getIdProveedor()
    {
        return txtIdProveedor.getText();
    }

    public String getNitProveedor()
    {
        return txtNitProveedor.getText();
    }

    public String getNombreProveedor()
    {
        return txtNombreProveedor.getText();
    }

    public String getTelefonoProveedor()
    {
        return txtTelefonoProveedor.getText();
    }

    public String getDireccionProveedor()
    {
        return txtDireccionProveedor.getText();
    }

    public String getRazonSocialProveedor()
    {
        return txtRazonSocialProveedor.getText();
    }

    //=====|Producto|=====//
    public String getIdProducto()
    {
        return txtIdProducto.getText();
    }

    public String getNombreProducto()
    {
        return txtNombreProveedor.getText();
    }

    public String getPrecioVentaProducto()
    {
        return txtPrecioVentaProducto.getText();
    }

    public String getStockProducto()
    {
        return txtStockProducto.getText();
    }

    //=====|Comprar|=====//
    public String getCodigoComprar()
    {
        return txtCodigoComprar.getText();
    }

    public String getNombreComprar()
    {
        return txtNombreComprar.getText();
    }

    public String getPrecioCompraComprar()
    {
        return txtPrecioCompraComprar.getText();
    }

    public String getPrecioVentaComprar()
    {
        return txtPrecioVentaComprar.getText();
    }

    public String getStockComprar()
    {
        return txtStockComprar.getText();
    }

    /*public Producto getProveedorComprar()
    {
        return jcbProveedorComprar.getSelectedItem();
    }*/

    //=====|Vender|=====//
    /*public Cliente getClienteVender()
    {
        return jcbClienteVender.getSelectedItem();
    }*/

    public String getStockVender()
    {
        return txtStockVender.getText();
    }

    /*public Producto getProductoVender()
    {
        return jcbProveedorComprar.getSelectedItem();
    }*/

    //==========|Rellenar y Vaciar JComboBox|==========//
    //=====|Comprar|=====//
    /*public void rellenarProveedorComprar(Proveedor auxProveedor)
    {
        jcbProveedorComprar.addItem(auxProveedor);
    }*/

    public void vaciarProveedorComprar()
    {
        jcbProveedorComprar.removeAllItems();
    }

    //=====|Vender|=====//
    /*public void agregarClienteVender(Cliente auxCliente)
    {
        jcbClienteVender.addItem(auxCliente);
    }*/

    public void vaciarClienteVender()
    {
        jcbClienteVender.removeAllItems();
    }

    /*public void agregarProductoVender(Producto auxProducto)
    {
        jcbClienteVender.addItem(auxProducto);
    }*/

    public void vaciarProductoVender()
    {
        jcbClienteVender.removeAllItems();
    }

    //==========|Mensajes Emergentes|==========//
    public void mostarMensajeError(String auxMensaje)
    {
        JOptionPane.showMessageDialog(this, auxMensaje, "", JOptionPane.ERROR_MESSAGE);
    }

    public void mostarMensaje(String auxMensaje)
    {
        JOptionPane.showMessageDialog(this, auxMensaje);
    }

    // Variables declaration - do not modify
    private JButton btnAgregarCliente;
    private JButton btnAgregarCompra;
    private JButton btnAgregarProveedor;
    private JButton btnAgregarVenta;
    private JButton btnClientes;
    private JButton btnComprar;
    private JButton btnCompras;
    private JButton btnEditarCliente;
    private JButton btnEditarProducto;
    private JButton btnEditarProveedor;
    private JButton btnEliminarCliente;
    private JButton btnEliminarCompra;
    private JButton btnEliminarProducto;
    private JButton btnEliminarProveedor;
    private JButton btnEliminarVenta;
    private JButton btnInventario;
    private JButton btnProveedores;
    private JButton btnRealizarCompra;
    private JButton btnRealizarVenta;
    private JButton btnVender;
    private JButton btnVentas;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcbClienteVender;
    private javax.swing.JComboBox<String> jcbProductoVender;
    private javax.swing.JComboBox<String> jcbProveedorComprar;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpBotonesCliente;
    private javax.swing.JPanel jpBotonesComprar;
    private javax.swing.JPanel jpBotonesInventario;
    private javax.swing.JPanel jpBotonesProveedor;
    private javax.swing.JPanel jpBotonesVender;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpComprar;
    private javax.swing.JPanel jpCompras;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JPanel jpFormularioCliente;
    private javax.swing.JPanel jpFormularioComprar;
    private javax.swing.JPanel jpFormularioComprar1;
    private javax.swing.JPanel jpFormularioInventario;
    private javax.swing.JPanel jpFormularioProveedor;
    private javax.swing.JPanel jpInferiorComprar;
    private javax.swing.JPanel jpInferiorCompras;
    private javax.swing.JPanel jpInferiorVender;
    private javax.swing.JPanel jpInferiorVentas;
    private javax.swing.JPanel jpInicial;
    private javax.swing.JPanel jpInventario;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpProveedor;
    private javax.swing.JPanel jpSuperiorCompras;
    private javax.swing.JPanel jpSuperiorVentas;
    private javax.swing.JPanel jpValoresTotales;
    private javax.swing.JPanel jpValoresTotalesVenta;
    private javax.swing.JPanel jpVender;
    private javax.swing.JPanel jpVentas;
    private javax.swing.JScrollPane jspTablaCliente;
    private javax.swing.JScrollPane jspTablaComprar;
    private javax.swing.JScrollPane jspTablaCompras;
    private javax.swing.JScrollPane jspTablaInventario;
    private javax.swing.JScrollPane jspTablaProveedor;
    private javax.swing.JScrollPane jspTablaVender;
    private javax.swing.JScrollPane jspTablaVentas;
    private JTable jtTablaCliente;
    private JTable jtTablaComprar;
    private JTable jtTablaCompras;
    private JTable jtTablaInventario;
    private JTable jtTablaProveedor;
    private JTable jtTablaVender;
    private JTable jtTablaVentas;
    private javax.swing.JLabel lblClienteVender;
    private javax.swing.JLabel lblCodigoCompra;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNitCliente;
    private javax.swing.JLabel lblNitProveedor;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreCompra;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblPrecioCompraComprar;
    private javax.swing.JLabel lblPrecioCompraProducto;
    private javax.swing.JLabel lblPrecioTotalComprar;
    private javax.swing.JLabel lblPrecioTotalVender;
    private javax.swing.JLabel lblPrecioVentaComprar;
    private javax.swing.JLabel lblPrecioVentaProducto;
    private javax.swing.JLabel lblProductoVender;
    private javax.swing.JLabel lblProductosTotalesComprar;
    private javax.swing.JLabel lblProductosTotalesVender;
    private javax.swing.JLabel lblProveedorComprar;
    private javax.swing.JLabel lblProveedorInventario;
    private javax.swing.JLabel lblRazonSocialProveedor;
    private javax.swing.JLabel lblStockComprar;
    private javax.swing.JLabel lblStockProducto;
    private javax.swing.JLabel lblStockVender;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblTelefonoProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigoComprar;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtNitCliente;
    private javax.swing.JTextField txtNitProveedor;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreComprar;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtPrecioCompraComprar;
    private javax.swing.JTextField txtPrecioCompraProducto;
    private javax.swing.JTextField txtPrecioVentaComprar;
    private javax.swing.JTextField txtPrecioVentaProducto;
    private javax.swing.JTextField txtProveedorProducto;
    private javax.swing.JTextField txtRazonSocialProveedor;
    private javax.swing.JTextField txtStockComprar;
    private javax.swing.JTextField txtStockProducto;
    private javax.swing.JTextField txtStockVender;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration
}
